#!/usr/bin/env python3
"""Build the deployable static site from the reference product surface.

`design/console.html` is authored for the Artifact runtime, which supplies the
document shell. A standalone deployment has to supply its own, so this wraps
the surface in a real document and derives the Content-Security-Policy from the
file rather than trusting a hand-maintained copy.

Inline style and script are hashed into the policy instead of allowing
'unsafe-inline'. The hashes are computed from the bytes actually shipped, so
the policy cannot drift away from the page.

Usage: python3 scripts/build_site.py
"""

from __future__ import annotations

import base64
import hashlib
import json
import re
import sys
from pathlib import Path

from build_fixture import build as build_fixture

sys.path.insert(0, str(Path(__file__).resolve().parent))
ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "design" / "console.html"
OUT_DIR = ROOT / "site"

TITLE = "Zolts — Program Console"
DESCRIPTION = (
    "The Zolts operator surface: a dense program list with evidence, per-play "
    "P&L and policy trace, where a lift that cannot be resolved is not reported."
)

DOCUMENT = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="description" content="{description}">
<meta name="color-scheme" content="dark">
<meta name="theme-color" content="#08090a">
<meta property="og:type" content="website">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{description}">
<link rel="icon" href="data:image/svg+xml,{favicon}">
{head}
</head>
<body>
{body}
</body>
</html>
"""

FAVICON = (
    "%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 18 18'%3E"
    "%3Crect width='18' height='18' rx='4' fill='%237d4bf5'/%3E"
    "%3Cpath d='M4 4h10L4 14h10' stroke='white' stroke-width='2' "
    "stroke-linecap='square' fill='none'/%3E%3C/svg%3E"
)


def sha256_csp(payload: str) -> str:
    digest = hashlib.sha256(payload.encode("utf-8")).digest()
    return "'sha256-" + base64.b64encode(digest).decode("ascii") + "'"


def build() -> None:
    source = SOURCE.read_text(encoding="utf-8")

    # The surface ships with its data inlined rather than fetched: it keeps
    # connect-src at 'none', avoids a round trip, and makes the page a single
    # self-contained file. The placeholder is replaced before hashing, so the
    # CSP covers the data as well as the code.
    fixture = json.dumps(build_fixture(), separators=(",", ":"))
    if "/*__FIXTURE__*/" not in source:
        raise SystemExit("design/console.html has no /*__FIXTURE__*/ placeholder")
    source = source.replace(
        '/*__FIXTURE__*/ {"programs":[],"decisions":{},"jurisdictions":[],"plannedPrograms":[]}',
        fixture, 1)

    # The surface authors <title>, <link> and <style> ahead of its markup; those
    # belong in the head, everything after belongs in the body.
    head_parts = re.findall(r"<title>.*?</title>|<link\b[^>]*>|<style>.*?</style>",
                            source, re.S)
    body = source
    for part in head_parts:
        body = body.replace(part, "", 1)
    body = body.strip()

    # Title is supplied by the document, not duplicated from the surface.
    head = "\n".join(p for p in head_parts if not p.startswith("<title>"))
    head = f"<title>{TITLE}</title>\n" + head

    document = DOCUMENT.format(
        title=TITLE, description=DESCRIPTION, favicon=FAVICON,
        head=head.strip(), body=body,
    )

    OUT_DIR.mkdir(exist_ok=True)
    (OUT_DIR / "index.html").write_text(document, encoding="utf-8")

    # Hash exactly what ships. 'unsafe-inline' would let any injected script
    # run; a hash allows precisely the one script this page contains.
    inline = re.findall(r"<style>(.*?)</style>|<script>(.*?)</script>", document, re.S)
    hashes = " ".join(sorted({sha256_csp(s or j) for s, j in inline}))

    # A hash covers a <style> element but never a style="" attribute, and the
    # surface sets transforms from data at runtime. Rather than weaken the whole
    # style-src, split it: stylesheet *elements* stay hash-locked, and only
    # inline *attributes* are allowed. script-src stays hash-locked either way,
    # which is where injection actually matters.
    policy = (
        "default-src 'self'; "
        f"style-src 'self' 'unsafe-inline' {hashes} https://fonts.googleapis.com; "
        f"style-src-elem 'self' {hashes} https://fonts.googleapis.com; "
        "style-src-attr 'unsafe-inline'; "
        "font-src https://fonts.gstatic.com; "
        f"script-src 'self' {hashes}; "
        "img-src 'self' data:; "
        "connect-src 'none'; "
        "object-src 'none'; "
        "base-uri 'none'; form-action 'none'; frame-ancestors 'self'"
    )

    (OUT_DIR / "_headers").write_text(
        "# Generated by scripts/build_site.py — do not edit by hand.\n"
        "/*\n"
        "  X-Frame-Options: SAMEORIGIN\n"
        "  X-Content-Type-Options: nosniff\n"
        "  Referrer-Policy: strict-origin-when-cross-origin\n"
        "  Permissions-Policy: geolocation=(), microphone=(), camera=()\n"
        f"  Content-Security-Policy: {policy}\n",
        encoding="utf-8",
    )

    vercel = {
        "$schema": "https://openapi.vercel.sh/vercel.json",
        "buildCommand": "python3 scripts/build_site.py",
        "outputDirectory": "site",
        "cleanUrls": True,
        "trailingSlash": False,
        "headers": [{
            "source": "/(.*)",
            "headers": [
                {"key": "X-Frame-Options", "value": "SAMEORIGIN"},
                {"key": "X-Content-Type-Options", "value": "nosniff"},
                {"key": "Referrer-Policy", "value": "strict-origin-when-cross-origin"},
                {"key": "Permissions-Policy", "value": "geolocation=(), microphone=(), camera=()"},
                {"key": "Content-Security-Policy", "value": policy},
            ],
        }],
    }
    (ROOT / "vercel.json").write_text(json.dumps(vercel, indent=2) + "\n", encoding="utf-8")

    print(f"site/index.html   {len(document):,} bytes, fixture inlined")
    print(f"site/_headers     CSP with {len(hashes.split())} inline hashes")
    print("vercel.json       regenerated with the same policy")


if __name__ == "__main__":
    build()
