#!/usr/bin/env python3
"""Build the deployable static site from the reference product surface.

The document assembly and the policy derivation live in `runtime/surface.py`,
because the API serves the same surface with live data. Two copies would drift,
and the copy that drifts is the one that ships a policy the page violates.

Usage: python3 scripts/build_site.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from build_fixture import build as build_fixture
from runtime.surface import (DESCRIPTION, TITLE, content_security_policy, document,
                             inject)

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "design" / "console.html"
OUT_DIR = ROOT / "site"


def build() -> None:
    source = SOURCE.read_text(encoding="utf-8")
    fixture = build_fixture()
    rendered = document(inject(source, fixture), title=TITLE, description=DESCRIPTION)

    OUT_DIR.mkdir(exist_ok=True)
    (OUT_DIR / "index.html").write_text(rendered, encoding="utf-8")

    # The same fixture, as data. It was written only when `build_fixture.py`
    # was run by hand, so CI's staleness check — which runs this file — could
    # never see it drift from the page beside it.
    (OUT_DIR / "data").mkdir(exist_ok=True)
    (OUT_DIR / "data" / "console.json").write_text(
        json.dumps(fixture, indent=2) + "\n", encoding="utf-8")

    # The static build fetches nothing, so connect-src stays closed.
    policy = content_security_policy(rendered, connect_src="'none'")

    (OUT_DIR / "_headers").write_text(
        "# Generated by scripts/build_site.py — do not edit by hand.\n"
        "/*\n"
        "  X-Frame-Options: SAMEORIGIN\n"
        "  X-Content-Type-Options: nosniff\n"
        "  Referrer-Policy: strict-origin-when-cross-origin\n"
        "  Permissions-Policy: geolocation=(), microphone=(), camera=()\n"
        f"  Content-Security-Policy: {policy}\n",
        encoding="utf-8",
    )

    vercel = {
        "$schema": "https://openapi.vercel.sh/vercel.json",
        # No build. `site/` is committed and CI regenerates it and fails on any
        # difference, so the host has nothing left to do but serve the files.
        #
        # Rebuilding here cost two failed deploys for nothing. The first had no
        # pyyaml, because CI installs it globally as its first step and so was
        # structurally unable to notice its absence. The second added a `pip
        # install` and hit PEP 668 — that image's Python is managed by uv and
        # refuses to be modified. Each fix would have been a guess about
        # somebody else's build image, to reproduce an artefact this repository
        # has already built and checked.
        "buildCommand": "",
        "outputDirectory": "site",
        "cleanUrls": True,
        "trailingSlash": False,
        "headers": [{
            "source": "/(.*)",
            "headers": [
                {"key": "X-Frame-Options", "value": "SAMEORIGIN"},
                {"key": "X-Content-Type-Options", "value": "nosniff"},
                {"key": "Referrer-Policy", "value": "strict-origin-when-cross-origin"},
                {"key": "Permissions-Policy", "value": "geolocation=(), microphone=(), camera=()"},
                {"key": "Content-Security-Policy", "value": policy},
            ],
        }],
    }
    (ROOT / "vercel.json").write_text(json.dumps(vercel, indent=2) + "\n", encoding="utf-8")

    print(f"site/index.html   {len(rendered):,} bytes, fixture inlined")
    print(f"site/_headers     CSP with {policy.count(chr(39) + 'sha256-')} hash references")
    print("vercel.json       regenerated with the same policy")


if __name__ == "__main__":
    build()
