#!/usr/bin/env python3
"""Build the deployable static site from the reference product surface.

The document assembly and the policy derivation live in `runtime/surface.py`,
because the API serves the same surface with live data. Two copies would drift,
and the copy that drifts is the one that ships a policy the page violates.

Usage: python3 scripts/build_site.py
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from build_fixture import build as build_fixture
from runtime.surface import (DESCRIPTION, TITLE, content_security_policy, document,
                             inject)

ROOT = Path(__file__).resolve().parent.parent

# The cadence the runtime wants, and the cadence that deploys.
#
# Vercel's Hobby plan accepts only daily crons, so a minute tick makes the
# platform refuse the build outright — `cron_jobs_limits_reached`. `docs/02`
# used to call that "the right failure", on the reasoning that a runtime which
# cannot tick should not pretend to. The cost of that stance was not visible
# until it was measured: every deploy had been failing, so the public URL
# served a build from before the brand, and nothing merged reached a reader.
#
# So the concession is explicit rather than silent. `hobby` is the default
# because it is what actually deploys; `pro` restores the cadence the runtime
# is designed for in one variable, the day the plan changes. Decision 43.
CRONS = {
    "pro": [
        {"path": "/api/tick", "schedule": "* * * * *"},
        {"path": "/api/watch", "schedule": "*/15 * * * *"},
    ],
    "hobby": [
        {"path": "/api/tick", "schedule": "0 3 * * *"},
        {"path": "/api/watch", "schedule": "0 4 * * *"},
    ],
}


def _plan() -> str:
    """Which cadence to write. An unknown plan is refused, not defaulted.

    A typo silently falling back to `hobby` would write a daily tick into a
    Pro deployment and look exactly like a working one.
    """
    plan = os.environ.get("ZOLTS_VERCEL_PLAN", "hobby").strip().lower()
    if plan not in CRONS:
        raise SystemExit(
            f"ZOLTS_VERCEL_PLAN is '{plan}'; it must be one of {sorted(CRONS)}")
    return plan

SOURCE = ROOT / "design" / "console.html"
OUT_DIR = ROOT / "site"


def build() -> None:
    source = SOURCE.read_text(encoding="utf-8")
    fixture = build_fixture()
    rendered = document(inject(source, fixture), title=TITLE, description=DESCRIPTION)

    OUT_DIR.mkdir(exist_ok=True)
    (OUT_DIR / "index.html").write_text(rendered, encoding="utf-8")

    # The same fixture, as data. It was written only when `build_fixture.py`
    # was run by hand, so CI's staleness check — which runs this file — could
    # never see it drift from the page beside it.
    (OUT_DIR / "data").mkdir(exist_ok=True)
    (OUT_DIR / "data" / "console.json").write_text(
        json.dumps(fixture, indent=2) + "\n", encoding="utf-8")

    # The static build fetches nothing, so connect-src stays closed.
    policy = content_security_policy(rendered, connect_src="'none'")

    (OUT_DIR / "_headers").write_text(
        "# Generated by scripts/build_site.py — do not edit by hand.\n"
        "/*\n"
        "  X-Frame-Options: SAMEORIGIN\n"
        "  X-Content-Type-Options: nosniff\n"
        "  Referrer-Policy: strict-origin-when-cross-origin\n"
        "  Permissions-Policy: geolocation=(), microphone=(), camera=()\n"
        f"  Content-Security-Policy: {policy}\n",
        encoding="utf-8",
    )

    vercel = {
        "$schema": "https://openapi.vercel.sh/vercel.json",
        # No build. `site/` is committed and CI regenerates it and fails on any
        # difference, so the host has nothing left to do but serve the files.
        #
        # Rebuilding here cost two failed deploys for nothing. The first had no
        # pyyaml, because CI installs it globally as its first step and so was
        # structurally unable to notice its absence. The second added a `pip
        # install` and hit PEP 668 — that image's Python is managed by uv and
        # refuses to be modified. Each fix would have been a guess about
        # somebody else's build image, to reproduce an artefact this repository
        # has already built and checked.
        "buildCommand": "",
        "outputDirectory": "site",
        "cleanUrls": True,
        "trailingSlash": False,
        # The runtime, as one function (ADR-041). `api/index.py` imports the
        # same FastAPI app the CLI serves. Rewrites run after the filesystem,
        # so `/` stays the static demo and every path it does not answer —
        # `/console`, `/health`, `/v1/*`, the cron's `/api/tick` — reaches the
        # API. `maxDuration` leaves a tick room to finish the pass it is in
        # when its own budget runs out; the budget itself is under a minute.
        "functions": {"api/index.py": {
            "maxDuration": 300,
            "excludeFiles": "{tests/**,site/**,docs/**,.github/**,**/__pycache__/**}",
        }},
        "rewrites": [{"source": "/(.*)", "destination": "/api/index"}],
        # Frankfurt, beside a database in eu-central-1. A function in
        # Washington talking to a database in Frankfurt pays the Atlantic on
        # every query, and a tick makes dozens.
        "regions": ["fra1"],
        # The worker, as a schedule. Both routes refuse a call without the
        # cron's bearer whatever the cadence is.
        "crons": CRONS[_plan()],
        # Production is released by the workflow that migrates and runs
        # preflight first. A push to `main` must not deploy around it, which
        # is what the platform's own git integration would do.
        "git": {"deploymentEnabled": {"main": False}},
        "headers": [
            {
                "source": "/(.*)",
                "headers": [
                    {"key": "X-Frame-Options", "value": "SAMEORIGIN"},
                    {"key": "X-Content-Type-Options", "value": "nosniff"},
                    {"key": "Referrer-Policy", "value": "strict-origin-when-cross-origin"},
                    {"key": "Permissions-Policy", "value": "geolocation=(), microphone=(), camera=()"},
                ],
            },
            # The static build's policy, on the static paths only. It closes
            # `connect-src` because the demo fetches nothing; the served
            # console sets its own policy and does fetch. Applied to every
            # path, this would break the product to protect the brochure.
            {"source": "/", "headers": [{"key": "Content-Security-Policy", "value": policy}]},
            {"source": "/data/(.*)",
             "headers": [{"key": "Content-Security-Policy", "value": policy}]},
        ],
    }
    (ROOT / "vercel.json").write_text(json.dumps(vercel, indent=2) + "\n", encoding="utf-8")

    print(f"site/index.html   {len(rendered):,} bytes, fixture inlined")
    print(f"site/_headers     CSP with {policy.count(chr(39) + 'sha256-')} hash references")
    print("vercel.json       regenerated: the same policy on the static paths, "
          "the runtime as a function, the worker as a cron")


if __name__ == "__main__":
    build()
